use_frameworks!

platform :ios, '8.0'

target 'ComponentMainModuleCategory_Example' do
  pod 'ComponentMainModuleCategory', :path => '../'

  target 'ComponentMainModuleCategory_Tests' do
    inherit! :search_paths

    
  end
end
